name: meow_dot # 项目名称 (根据你创建项目时的名称可能需要调整)
description: A macOS productivity toolkit with screenshot, pin, timer, and clock features. # 项目描述
publish_to: 'none' # 防止意外发布到 pub.dev

version: 1.0.0+1 # 应用版本号

environment:
  sdk: '>=3.0.0 <4.0.0' # 指定 Dart SDK 版本约束

dependencies:
  flutter:
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.2 # (如果用到 iOS 风格图标)
  # macos_ui: ^latest # (根据需要取消注释)
  # fluent_ui: ^latest # (根据需要取消注释)

  # State Management & DI
  flutter_bloc: ^8.1.5 # Bloc 状态管理
  equatable: ^2.0.5 # 简化对象比较
  get_it: ^7.7.0 # 服务定位器 (依赖注入)
  injectable: ^2.4.1 # 配合 get_it 生成代码

  # Features & System Interaction
  window_manager: ^0.3.8 # 窗口管理 (置顶, 大小, 位置)
  system_tray: ^2.0.3 # 系统托盘图标和菜单
  hotkey_manager: ^0.2.2 # 全局快捷键
  # desktop_screenshot: ^latest # 或 screen_capturer (根据实际选择和测试情况添加)
  # google_mlkit_text_recognition: ^latest # (或准备 Platform Channels)
  http: ^1.2.1 # 网络请求 (翻译, 更新)
  flutter_markdown: ^0.7.1 # Markdown 渲染
  shared_preferences: ^2.2.3 # 存储简单用户偏好
  path_provider: ^2.1.3 # 获取文件系统路径
  flutter_local_notifications: ^17.1.2 # 本地通知 (计时器提醒)
  package_info_plus: ^8.0.0 # 获取应用信息 (版本检查)
  url_launcher: ^6.3.0 # 打开 URL (下载新版本)
  # flutter_dotenv: ^latest # (如果需要管理 .env 文件)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # 代码规范检查
  build_runner: ^2.4.10 # 代码生成器
  injectable_generator: ^2.6.1 # DI 代码生成

flutter:
  uses-material-design: true # 即使是 macOS 应用，有时也需要 Material 组件

  # Assets (示例)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts (示例)
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/MyCustomFont-Regular.ttf
  #       - asset: assets/fonts/MyCustomFont-Bold.ttf
  #         weight: 700

