name: meow_dot # 项目名称 (根据你创建项目时的名称可能需要调整)
description: A macOS productivity toolkit with screenshot, pin, timer, and clock features. # 项目描述
publish_to: 'none' # 防止意外发布到 pub.dev

version: 1.0.0+1 # 应用版本号

environment:
  sdk: '>=3.0.0 <4.0.0' # 指定 Dart SDK 版本约束

dependencies:
  flutter:
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.2 # (如果用到 iOS 风格图标)
  # macos_ui: ^latest # (根据需要取消注释)
  # fluent_ui: ^latest # (根据需要取消注释)

  # State Management & DI
  flutter_bloc: ^8.1.5 # Bloc 状态管理
  equatable: ^2.0.5 # 简化对象比较
  get_it: ^7.7.0 # 服务定位器 (依赖注入)
  injectable: ^2.4.1 # 配合 get_it 生成代码

  # Features & System Interaction
  window_manager: 0.3.7 # Keep downgraded version for now
  system_tray: ^2.0.3
  hotkey_manager: ^0.2.2
  desktop_multi_window: ^0.2.1 # <--- 添加多窗口包
  # desktop_screenshot: ^latest
  # google_mlkit_text_recognition: ^latest
  http: ^1.2.1
  flutter_markdown: ^0.7.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.1.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  # flutter_dotenv: ^latest
  uuid: ^3.0.7 # 兼容 system_tray

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # 代码规范检查
  build_runner: ^2.4.10 # 代码生成器
  injectable_generator: ^2.6.1 # DI 代码生成

flutter:
  uses-material-design: true # 即使是 macOS 应用，有时也需要 Material 组件

  # Assets (示例)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts (示例)
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/MyCustomFont-Regular.ttf
  #       - asset: assets/fonts/MyCustomFont-Bold.ttf
  #         weight: 700
